---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/13 10:39
---


function tttt()
    -- local sql = "insert into as_user_signing(number,appId,provinceId) values ('8618032165385','0002010000000003','3217')"
    --  local res, errinfo = asDBClient.sqlRun(sql)
    local resultBody = {
        ["jieguo"] = true
    }
    --  local res = false
    -- if not res  then
    -- resultBody[jieguo] = false
    --   return sendAck({ Retn = "500", Desc = "fail" }, resultBody)
    -- else
    --   resultBody[jieguo] = true
    --     return sendAck({ Retn = "200", Desc = "ok" }, resultBody)
    --   end
    return sendAck({Retn = "200",Desc = "ok"}, resultBody)
end

function mupdate()
    local number = "8618032165385"
    local appId = "0002010000000004"
    local sql = "update as_user_signing set appId = '%s' where number = '%s'"
    sql = string.format(sql,appId,number)
    local res, errinfo = asDBClient.sqlRun(sql)
    local resultBody = {
        ["jieguo"] = false
    }
     if not res  then
       resultBody["jieguo"] = false
     return sendAck({ Retn = "500", Desc = "fail" }, resultBody)
     else
       resultBody["jieguo"] = true
     return sendAck({ Retn = "200", Desc = "ok" }, resultBody)
     end
end

function mdelete()
    local number = "8618032165385"
    local appId = "0002010000000004"
    local sql = "delete  from as_user_signing where number = '%s'"
    sql = string.format(sql,number)
    local res, errinfo = asDBClient.sqlRun(sql)
    local resultBody = {
        ["jieguo"] = false
    }
    if not res  then
        resultBody["jieguo"] = false
        return sendAck({ Retn = "500", Desc = "fail" }, resultBody)
    else
        resultBody["jieguo"] = true
        return sendAck({ Retn = "200", Desc = "ok" }, resultBody)
    end
end


