---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/14 16:20
---

function user_sign(argt)
    local body = nil
    local headerUrl = as.getUrl()
    local strTb = strex.str2Tab(headerUrl,"/")
    local number = strTb[#strTb]
    local appUrl = strTb[#strTb-3]
    if isNull(argt.appIds) == false and isNull(argt.province) == false then
        local appIds = argt.appIds
        if existsAppid(appUrl,appIds[1]) == false then
            wornf("find appid:%s  not exists",appIds[1])
            body = {
                ["code"] = "00000001",["description"] = "find no appid"
            }
            return sendAck({Retn = "500",Desc = "fail"},body)
        end
        --暂时无需判断翻译签约的是什么，根据用户级别开关数据进行判断
        --local appid = appIds[1]
        --if appid == translationAppid and isNull(argt.subAppType) == true then
        --    warnf("some required param can not be nil,appIds = %s,province = %s",argt.appIds,argt.province)
        --    body = {
        --        ["code"] = "00000002",["description"] = "Invalid input value"
        --    }
        --    return sendAck({Retn = "400", Desc = "fail"}, body)
        --end
        local provinceId = argt.province
        local result = sign_biz(number,appIds,provinceId)
        if result ~= true then
            body = {
                ["code"] = "00000001",["description"] = "found error when sign insert db"
            }
            return sendAck

        end
    end
end
