---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/13 11:28
---



function test(args)
    resultBody = {
        ["a"] = 1,
        ["b"] = 2,
        ["c"] = 3,
        ["d"] = 4,
        ["e"] = 5,
    }
    return sendAck({ Retn = "200", Desc = "OK" }, resultBody)
end
