---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/2 15:42
---
--print("hello world!")
--print("Hello World！")
--print("www.runoob.com")
--b=20
--print(b)
--html = [[
--<html>
--<head></head>
--<body>
--    <a href="http://www.runoob.com/">菜鸟教程</a>
--</body>
--</html>
--]]
--print(html)
--print("12abc".."d")
--print(#"www.runoob.com")
--
--local tbl1 = {}
--local tbl2 = {"apple",pear}
--print(tbl2)
--a = {}
--a["key"] = "value"
--key = 10
--a[key] = 22
--a[key] = a[key] + 11
--for k, v in pairs(a) do
--    print(k .. " : " .. v)
--end

--local tbl = {"apple", "pear", "orange", "grape"}
--for key, val in pairs(tbl) do
--    print("Key", key)
--end

--a3 = {}
--for i = 1, 11 do
--    a3[i] = i
--end
----a3["key"] = "val"
----print(a3["key"])
----print(a3["none"])
--
--for i, v in ipairs(a3) do
--    print(i.." : "..v)
--end

--
--function factorial1(n)
--    if n == 0 then
--        return 1
--    else
--        return n * factorial1(n-1)
--    end
--end
--
--print(factorial1(5))
--
--a, b, c = 0, 1
--print(a,b,c)
--a, b = a+1, b+1, b+2
--print(a,b)
--
--a, b, c = 0
--print(a,b,c)


--i=1
--while(i<10)
--do
--    print(i)
--    i=i+1
--end

--for i = 1, 10 do
--    print(i)
--end

--i = 1
--repeat
--    print(i)
--    i=i+1
--until i==10


--if(0)
--then
--    print("0wei")
--end

--a = 21
--b = 5
--print(b/a)
--string1 = "Lua"
--print("\"字符串 1 是\"",string1)


--function square(iteratorMaxCount,currentNumber)
--    if currentNumber<iteratorMaxCount
--    then
--        currentNumber = currentNumber+1
--        return currentNumber, currentNumber*currentNumber
--    end
--end
--
--for i,n in square,30,0
--do
--    print(i,n)
--end
--
--
--function iter (a, i)
--    i = i + 1
--    local v = a[i]
--    if v then
--        return i, v
--    end
--end
--
--function ipairs (a)
--    return iter, a, 0
--end
--
--
--print(ipairs(30))


--languageConfig = {
--    ["CHINESE"] = "zh",
--    ["ENGLISH"] = "en",
--    ["JAPANESE"] = "ja",
--    ["KOREAN"] = "kr",
--    ["ARABIC"] = "ar",
--    ["RUSSIAN"] = "ru"
--}
--
--print(type(languageConfig))
--print(languageConfig["CHINESE"])


--for i=1,31 do
--    local provinceId = string.format("%02d",i)
--    print(provinceId)
--end

--print(httpUtil.httpsend("www.baidu.com","GET"))

--a = {
--    [1]="da",
--    [2]="ad"
--}
--print(a[3])

--local r = {
--    retn = "0000"
--}
----print(type(r.body))
----print(r.body)
----if r.body then
----    print("123")
----end
--r.body = "123"
--print(r.body)

--
--a = 0 or 2
--print(a)

--value = 121313212312312
--if not value  or type(value) == "userdata" then
--    print("true")
--else
--    print("false")
--end
--
--function isNull(value)
--    if not value or type(value) == "userdata" then
--        return true
--    else
--        return false
--    end
--end
--print((value or type(value)))



--local a = "dada"
--
--print(string.sub(a,1,#a))

--function jiechen(a)
--    if a==0 then
--        return 1
--    else
--        return a * jiechen(a-1)
--    end
--end
--print(jiechen(5))


--local s = "e*234"
--print(string.gsub(s,"*","E"))


res = {
    [1] = 1,
    [2] = 2,
    [3] = 3
}
local digitMap =""
for i = 1, #res do
    digitMap=digitMap..res[i]..( i == #res and "" or "|")
end
print(digitMap)