---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/13 10:44
---

VERSION = "1.1.2"
--日志声明
SLOG_CLASS = "DEBUG"

include "abc"
include "astest"

include "httpUtil"

asDBClient = mysql or {}

function _slinit()
    asDBClient  = mysql.init("MysqlDB","astest")
    --6.4.5请求下发业务设置接口
    --firstRequest(funtelAppid,curHost.."/v1/as/getresult/"..funtelAppid)
    --firstRequest(translationAppid,curHost.."/v1/as/getresult/"..translationAppid)
    --firstRequest(digitalHumanAppid,curHost.."/v1/as/getresult/"..digitalHumanAppid)
end




lib_cmdtable = {
    --    ["GET /v1/mysqlt"] = tttt,
    ["GET /v1/ttt"] = test
}