---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/10 14:18
---


-- 导入 LuaSocket 库
local socket = require("socket")

-- 创建 TCP 连接
local client = socket.tcp()

-- 连接到远程服务器
client:connect("10.1.115.72", 8180)

-- 发送 GET 请求
client:send("POST / HTTP/2.0\r\nHost: v1/jisuan/5\r\n\r\n")

-- 接收响应
local response = client:receive()

-- 打印响应内容
print(response)

-- 关闭连接
client:close()