---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86187.
--- DateTime: 2023/11/15 10:36
---


function getversion()
    resultBody = {
        ["version"] = VERSION
    }
    return sendAck({Retn = "200",Desc = "ok"}, resultBody)
end